CREATE TABLE NHLstats
	(
	dfIndex number,	
	faceoffWinPctg number,	
	faceoffsLost number,	
	faceoffsWon number,	
	gameDate date,	
	gameId number,	
	gameLocationCode varchar2(2),	
	gamesPlayed number,	
	goalsAgainst number,	
	goalsFor number,	
	losses number,	
	opponentTeamAbbrev varchar2(4),	
	otLosses number,	
	penaltyKillPctg number,	
	points number,	
	ppGoalsAgainst number,	
	ppGoalsFor number,	
	ppOpportunities number,	
	ppPctg number,	
	shNumTimes number,	
	shootoutGamesLost number,	
	shootoutGamesWon number,	
	shotsAgainst number,	
	shotsFor number,	
	teamAbbrev varchar2(4),	
	teamFullName varchar2(50),	
	teamId number,	
	ties number,	
	wins number,	
	franchiseCommonName varchar2(25),	
	franchiseId number,	
	franchisePlaceName varchar2(25),	
	ppAssists number,	
	ppFaceoffsLost number,	
	ppFaceoffsWon number,	
	ppGiveaways number,	
	ppTakeaways number,	
	ppTimeOnIce number,	
	penaltyKills number,	
	shFaceoffsLost number,	
	shFaceoffsWon number,	
	shGoalsAgainst number,	
	shGoalsFor number,	
	shTimeOnIce number,	
	penalties number,	
	penaltiesGameMisconduct number,	
	penaltiesMajor number,	
	penaltiesMatch number,	
	penaltiesMinor number,	
	penaltiesMisconduct number,	
	penaltyMinutes number,	
	blockedShots number,	
	faceoffs number,	
	giveaways number,	
	hits number,	
	shootingPctg number,	
	takeaways number,	
	evFaceoffsLost number,	
	evFaceoffsWon number,	
	enGoalsFor number,	
	evGoalsFor number,	
	otGamesPlayed number,	
	otGoals number,	
	penaltyShotAttempts number,	
	penaltyShotGoals number,	
	daysBtwGamesGroup varchar2(3),	
	shotAttempts number,	
	shotAttemptsAgainst number,	
	shotAttemptsAhead number,	
	shotAttemptsBehind number,	
	shotAttemptsClose number,	
	shotAttemptsFor number,	
	shotAttemptsTied number,	
	unblockedShotAttempts number,	
	unblockedShotAttemptsAgainst number,	
	unblockedShotAttemptsAhead number,	
	unblockedShotAttemptsBehind number,	
	unblockedShotAttemptsClose number,	
	unblockedShotAttemptsFor number,	
	unblockedShotAttemptsTied number,	
	defensiveZoneFaceoffs number,	
	fiveOnFiveSavePctg number,	
	fiveOnFiveShootingPctg number,	
	offensiveZoneFaceoffs number,	
	shootingPlusSavePctg number,	
	shotAttemptsPctg number,	
	shotAttemptsPctgAhead number,	
	shotAttemptsPctgBehind number,	
	shotAttemptsPctgClose number,	
	shotAttemptsPctgTied number,	
	unblockedShotAttemptsPctg number,	
	unblockedShotAttemptsPctgAhead number,	
	unblockedShotAttemptsPctgBehin number,	
	unblockedShotAttemptsPctgClose number,	
	unblockedShotAttemptsPctgTied number,	
	zoneStartPctg number,	
	assist1st number,	
	assist2nd number,	
	assistsPer60Minutes number,	
	avgShotLength number,	
	goalsPer60Minutes number,	
	penaltiesDrawnPer60Minutes number,	
	penaltiesPer60Minutes number,	
	pointsPer60Minutes number,	
	shots number,	
	faceoffLoss number,	
	faceoffLossDefensiveZone number,	
	faceoffLossNeutralZone number,	
	faceoffLossOffensiveZone number,	
	faceoffLossWhenAhead number,	
	faceoffLossWhenBehind number,	
	faceoffLossWhenClose number,	
	faceoffWinPctgDefensiveZone number,	
	faceoffWinPctgNeutralZone number,	
	faceoffWinPctgOffensiveZone number,	
	faceoffWins number,	
	faceoffWinsDefensiveZone number,	
	faceoffWinsNeutralZone number,	
	faceoffWinsOffensiveZone number,	
	faceoffWinsWhenAhead number,	
	faceoffWinsWhenBehind number,	
	faceoffWinsWhenClose number,	
	faceoffsTaken number,	
	goals number,	
	goalsBackhand number,	
	goalsDeflected number,	
	goalsSlap number,	
	goalsSnap number,	
	goalsTipped number,	
	goalsWraparound number,	
	goalsWrist number,	
	missedShots number,	
	missedShotsHitCrossbar number,	
	missedShotsHitPost number,	
	missedShotsOverNet number,	
	missedShotsWideOfNet number,	
	shotsBackhand number,	
	shotsDeflected number,	
	shotsSlap number,	
	shotsSnap number,	
	shotsTipped number,	
	shotsWraparound number,	
	shotsWrist number,	
	shootoutGamesPlayed number,	
	shootoutGoals number,	
	shootoutGoalsAgainst number,	
	shootoutSavePctg number,	
	shootoutSaves number,	
	shootoutShootingPctg number,	
	shootoutShots number,	
	shootoutShotsAgainst number
	);

CREATE TABLE NHLstats_load
	(
	dfIndex number,	
	faceoffWinPctg number,	
	faceoffsLost number,	
	faceoffsWon number,	
	gameDate varchar2(50),	
	gameId number,	
	gameLocationCode varchar2(2),	
	gamesPlayed number,	
	goalsAgainst number,	
	goalsFor number,	
	losses number,	
	opponentTeamAbbrev varchar2(4),	
	otLosses number,	
	penaltyKillPctg number,	
	points number,	
	ppGoalsAgainst number,	
	ppGoalsFor number,	
	ppOpportunities number,	
	ppPctg number,	
	shNumTimes number,	
	shootoutGamesLost number,	
	shootoutGamesWon number,	
	shotsAgainst number,	
	shotsFor number,	
	teamAbbrev varchar2(4),	
	teamFullName varchar2(50),	
	teamId number,	
	ties number,	
	wins number,	
	franchiseCommonName varchar2(25),	
	franchiseId number,	
	franchisePlaceName varchar2(25),	
	ppAssists number,	
	ppFaceoffsLost number,	
	ppFaceoffsWon number,	
	ppGiveaways number,	
	ppTakeaways number,	
	ppTimeOnIce number,	
	penaltyKills number,	
	shFaceoffsLost number,	
	shFaceoffsWon number,	
	shGoalsAgainst number,	
	shGoalsFor number,	
	shTimeOnIce number,	
	penalties number,	
	penaltiesGameMisconduct number,	
	penaltiesMajor number,	
	penaltiesMatch number,	
	penaltiesMinor number,	
	penaltiesMisconduct number,	
	penaltyMinutes number,	
	blockedShots number,	
	faceoffs number,	
	giveaways number,	
	hits number,	
	shootingPctg number,	
	takeaways number,	
	evFaceoffsLost number,	
	evFaceoffsWon number,	
	enGoalsFor number,	
	evGoalsFor number,	
	otGamesPlayed number,	
	otGoals number,	
	penaltyShotAttempts number,	
	penaltyShotGoals number,	
	daysBtwGamesGroup varchar2(3),	
	shotAttempts number,	
	shotAttemptsAgainst number,	
	shotAttemptsAhead number,	
	shotAttemptsBehind number,	
	shotAttemptsClose number,	
	shotAttemptsFor number,	
	shotAttemptsTied number,	
	unblockedShotAttempts number,	
	unblockedShotAttemptsAgainst number,	
	unblockedShotAttemptsAhead number,	
	unblockedShotAttemptsBehind number,	
	unblockedShotAttemptsClose number,	
	unblockedShotAttemptsFor number,	
	unblockedShotAttemptsTied number,	
	defensiveZoneFaceoffs number,	
	fiveOnFiveSavePctg number,	
	fiveOnFiveShootingPctg number,	
	offensiveZoneFaceoffs number,	
	shootingPlusSavePctg number,	
	shotAttemptsPctg number,	
	shotAttemptsPctgAhead number,	
	shotAttemptsPctgBehind number,	
	shotAttemptsPctgClose number,	
	shotAttemptsPctgTied number,	
	unblockedShotAttemptsPctg number,	
	unblockedShotAttemptsPctgAhead number,	
	unblockedShotAttemptsPctgBehin number,	
	unblockedShotAttemptsPctgClose number,	
	unblockedShotAttemptsPctgTied number,	
	zoneStartPctg number,	
	assist1st number,	
	assist2nd number,	
	assistsPer60Minutes number,	
	avgShotLength number,	
	goalsPer60Minutes number,	
	penaltiesDrawnPer60Minutes number,	
	penaltiesPer60Minutes number,	
	pointsPer60Minutes number,	
	shots number,	
	faceoffLoss number,	
	faceoffLossDefensiveZone number,	
	faceoffLossNeutralZone number,	
	faceoffLossOffensiveZone number,	
	faceoffLossWhenAhead number,	
	faceoffLossWhenBehind number,	
	faceoffLossWhenClose number,	
	faceoffWinPctgDefensiveZone number,	
	faceoffWinPctgNeutralZone number,	
	faceoffWinPctgOffensiveZone number,	
	faceoffWins number,	
	faceoffWinsDefensiveZone number,	
	faceoffWinsNeutralZone number,	
	faceoffWinsOffensiveZone number,	
	faceoffWinsWhenAhead number,	
	faceoffWinsWhenBehind number,	
	faceoffWinsWhenClose number,	
	faceoffsTaken number,	
	goals number,	
	goalsBackhand number,	
	goalsDeflected number,	
	goalsSlap number,	
	goalsSnap number,	
	goalsTipped number,	
	goalsWraparound number,	
	goalsWrist number,	
	missedShots number,	
	missedShotsHitCrossbar number,	
	missedShotsHitPost number,	
	missedShotsOverNet number,	
	missedShotsWideOfNet number,	
	shotsBackhand number,	
	shotsDeflected number,	
	shotsSlap number,	
	shotsSnap number,	
	shotsTipped number,	
	shotsWraparound number,	
	shotsWrist number,	
	shootoutGamesPlayed number,	
	shootoutGoals number,	
	shootoutGoalsAgainst number,	
	shootoutSavePctg number,	
	shootoutSaves number,	
	shootoutShootingPctg number,	
	shootoutShots number,	
	shootoutShotsAgainst number	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('NHLstats.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO NHLstats
	(
	dfIndex,	
	faceoffWinPctg,	
	faceoffsLost,	
	faceoffsWon,	
	gameDate,	
	gameId,	
	gameLocationCode,	
	gamesPlayed,	
	goalsAgainst,	
	goalsFor,	
	losses,	
	opponentTeamAbbrev,	
	otLosses,	
	penaltyKillPctg,	
	points,	
	ppGoalsAgainst,	
	ppGoalsFor,	
	ppOpportunities,	
	ppPctg,	
	shNumTimes,	
	shootoutGamesLost,	
	shootoutGamesWon,	
	shotsAgainst,	
	shotsFor,	
	teamAbbrev,	
	teamFullName,	
	teamId,	
	ties,	
	wins,	
	franchiseCommonName,	
	franchiseId,	
	franchisePlaceName,	
	ppAssists,	
	ppFaceoffsLost,	
	ppFaceoffsWon,	
	ppGiveaways,	
	ppTakeaways,	
	ppTimeOnIce,	
	penaltyKills,	
	shFaceoffsLost,	
	shFaceoffsWon,	
	shGoalsAgainst,	
	shGoalsFor,	
	shTimeOnIce,	
	penalties,	
	penaltiesGameMisconduct,	
	penaltiesMajor,	
	penaltiesMatch,	
	penaltiesMinor,	
	penaltiesMisconduct,	
	penaltyMinutes,	
	blockedShots,	
	faceoffs,	
	giveaways,	
	hits,	
	shootingPctg,	
	takeaways,	
	evFaceoffsLost,	
	evFaceoffsWon,	
	enGoalsFor,	
	evGoalsFor,	
	otGamesPlayed,	
	otGoals,	
	penaltyShotAttempts,	
	penaltyShotGoals,	
	daysBtwGamesGroup,	
	shotAttempts,	
	shotAttemptsAgainst,	
	shotAttemptsAhead,	
	shotAttemptsBehind,	
	shotAttemptsClose,	
	shotAttemptsFor,	
	shotAttemptsTied,	
	unblockedShotAttempts,	
	unblockedShotAttemptsAgainst,	
	unblockedShotAttemptsAhead,	
	unblockedShotAttemptsBehind,	
	unblockedShotAttemptsClose,	
	unblockedShotAttemptsFor,	
	unblockedShotAttemptsTied,	
	defensiveZoneFaceoffs,	
	fiveOnFiveSavePctg,	
	fiveOnFiveShootingPctg,	
	offensiveZoneFaceoffs,	
	shootingPlusSavePctg,	
	shotAttemptsPctg,	
	shotAttemptsPctgAhead,	
	shotAttemptsPctgBehind,	
	shotAttemptsPctgClose,	
	shotAttemptsPctgTied,	
	unblockedShotAttemptsPctg,	
	unblockedShotAttemptsPctgAhead,	
	unblockedShotAttemptsPctgBehin,	
	unblockedShotAttemptsPctgClose,	
	unblockedShotAttemptsPctgTied,	
	zoneStartPctg,	
	assist1st,	
	assist2nd,	
	assistsPer60Minutes,	
	avgShotLength,	
	goalsPer60Minutes,	
	penaltiesDrawnPer60Minutes,	
	penaltiesPer60Minutes,	
	pointsPer60Minutes,	
	shots,	
	faceoffLoss,	
	faceoffLossDefensiveZone,	
	faceoffLossNeutralZone,	
	faceoffLossOffensiveZone,	
	faceoffLossWhenAhead,	
	faceoffLossWhenBehind,	
	faceoffLossWhenClose,	
	faceoffWinPctgDefensiveZone,	
	faceoffWinPctgNeutralZone,	
	faceoffWinPctgOffensiveZone,	
	faceoffWins,	
	faceoffWinsDefensiveZone,	
	faceoffWinsNeutralZone,	
	faceoffWinsOffensiveZone,	
	faceoffWinsWhenAhead,	
	faceoffWinsWhenBehind,	
	faceoffWinsWhenClose,	
	faceoffsTaken,	
	goals,	
	goalsBackhand,	
	goalsDeflected,	
	goalsSlap,	
	goalsSnap,	
	goalsTipped,	
	goalsWraparound,	
	goalsWrist,	
	missedShots,	
	missedShotsHitCrossbar,	
	missedShotsHitPost,	
	missedShotsOverNet,	
	missedShotsWideOfNet,	
	shotsBackhand,	
	shotsDeflected,	
	shotsSlap,	
	shotsSnap,	
	shotsTipped,	
	shotsWraparound,	
	shotsWrist,	
	shootoutGamesPlayed,	
	shootoutGoals,	
	shootoutGoalsAgainst,	
	shootoutSavePctg,	
	shootoutSaves,	
	shootoutShootingPctg,	
	shootoutShots,	
	shootoutShotsAgainst	
	)
	(
	SELECT dfIndex,	
		faceoffWinPctg,	
		faceoffsLost,	
		faceoffsWon,	
		TRUNC(TO_TIMESTAMP_TZ(gameDate, 'YYYY-MM-DD HH24:MI:SS TZH:TZM')) gameDate,	
		gameId,	
		gameLocationCode,	
		gamesPlayed,	
		goalsAgainst,	
		goalsFor,	
		losses,	
		opponentTeamAbbrev,	
		otLosses,	
		penaltyKillPctg,	
		points,	
		ppGoalsAgainst,	
		ppGoalsFor,	
		ppOpportunities,	
		ppPctg,	
		shNumTimes,	
		shootoutGamesLost,	
		shootoutGamesWon,	
		shotsAgainst,	
		shotsFor,	
		teamAbbrev,	
		teamFullName,	
		teamId,	
		ties,	
		wins,	
		franchiseCommonName,	
		franchiseId,	
		franchisePlaceName,	
		ppAssists,	
		ppFaceoffsLost,	
		ppFaceoffsWon,	
		ppGiveaways,	
		ppTakeaways,	
		ppTimeOnIce,	
		penaltyKills,	
		shFaceoffsLost,	
		shFaceoffsWon,	
		shGoalsAgainst,	
		shGoalsFor,	
		shTimeOnIce,	
		penalties,	
		penaltiesGameMisconduct,	
		penaltiesMajor,	
		penaltiesMatch,	
		penaltiesMinor,	
		penaltiesMisconduct,	
		penaltyMinutes,	
		blockedShots,	
		faceoffs,	
		giveaways,	
		hits,	
		shootingPctg,	
		takeaways,	
		evFaceoffsLost,	
		evFaceoffsWon,	
		enGoalsFor,	
		evGoalsFor,	
		otGamesPlayed,	
		otGoals,	
		penaltyShotAttempts,	
		penaltyShotGoals,	
		daysBtwGamesGroup,	
		shotAttempts,	
		shotAttemptsAgainst,	
		shotAttemptsAhead,	
		shotAttemptsBehind,	
		shotAttemptsClose,	
		shotAttemptsFor,	
		shotAttemptsTied,	
		unblockedShotAttempts,	
		unblockedShotAttemptsAgainst,	
		unblockedShotAttemptsAhead,	
		unblockedShotAttemptsBehind,	
		unblockedShotAttemptsClose,	
		unblockedShotAttemptsFor,	
		unblockedShotAttemptsTied,	
		defensiveZoneFaceoffs,	
		fiveOnFiveSavePctg,	
		fiveOnFiveShootingPctg,	
		offensiveZoneFaceoffs,	
		shootingPlusSavePctg,	
		shotAttemptsPctg,	
		shotAttemptsPctgAhead,	
		shotAttemptsPctgBehind,	
		shotAttemptsPctgClose,	
		shotAttemptsPctgTied,	
		unblockedShotAttemptsPctg,	
		unblockedShotAttemptsPctgAhead,	
		unblockedShotAttemptsPctgBehin,	
		unblockedShotAttemptsPctgClose,	
		unblockedShotAttemptsPctgTied,	
		zoneStartPctg,	
		assist1st,	
		assist2nd,	
		assistsPer60Minutes,	
		avgShotLength,	
		goalsPer60Minutes,	
		penaltiesDrawnPer60Minutes,	
		penaltiesPer60Minutes,	
		pointsPer60Minutes,	
		shots,	
		faceoffLoss,	
		faceoffLossDefensiveZone,	
		faceoffLossNeutralZone,	
		faceoffLossOffensiveZone,	
		faceoffLossWhenAhead,	
		faceoffLossWhenBehind,	
		faceoffLossWhenClose,	
		faceoffWinPctgDefensiveZone,	
		faceoffWinPctgNeutralZone,	
		faceoffWinPctgOffensiveZone,	
		faceoffWins,	
		faceoffWinsDefensiveZone,	
		faceoffWinsNeutralZone,	
		faceoffWinsOffensiveZone,	
		faceoffWinsWhenAhead,	
		faceoffWinsWhenBehind,	
		faceoffWinsWhenClose,	
		faceoffsTaken,	
		goals,	
		goalsBackhand,	
		goalsDeflected,	
		goalsSlap,	
		goalsSnap,	
		goalsTipped,	
		goalsWraparound,	
		goalsWrist,	
		missedShots,	
		missedShotsHitCrossbar,	
		missedShotsHitPost,	
		missedShotsOverNet,	
		missedShotsWideOfNet,	
		shotsBackhand,	
		shotsDeflected,	
		shotsSlap,	
		shotsSnap,	
		shotsTipped,	
		shotsWraparound,	
		shotsWrist,	
		shootoutGamesPlayed,	
		shootoutGoals,	
		shootoutGoalsAgainst,	
		shootoutSavePctg,	
		shootoutSaves,	
		shootoutShootingPctg,	
		shootoutShots,	
		shootoutShotsAgainst
	FROM NHLstats_load
	);
