test = {
'base_ic' : 136,
'SUPPLIES': 500,
'FUEL': 40,
'MONEY' : 70,
'CRUDE_OIL': 500,
'METAL' : 1000,
'ENERGY' : 1000,
'RARE_MATERIALS': 40000,
'CRUDE_OIL_PRO': 2,
'METAL_PRO' : 140,
'ENERGY_PRO' : 592,
'RARE_MATERIALS_PRO': 68,
'manpower' : 850,
'head_of_state' : 'power_hungry_demagogue',
'head_of_government' : 'silent_workhorse',
'foreign_minister' : 'great_compromiser',
'armament_minister' : 'infantry_proponent',
'minister_of_security' : 'prince_of_terror',
'minister_of_intelligence' : 'dismal_enigma',
'chief_of_staff' : 'school_of_manoeuvre',
'chief_of_army' : 'armoured_spearhead_doctrine',
'chief_of_navy' : 'decisive_naval_battle_doctrine',
'chief_of_air' : 'army_aviation_doctrine',

'infantry_theory' : 10,
'infantry_practical' : 10,
'militia_theory' : 2.5,
'militia_practical' : 2.5,
'mobile_theory' : 5,
'mobile_practical' : 5,
'artillery_theory' : 10 ,
'artillery_practical' : 10 ,
'rocket_science' : 5,
'rocket_practical' : 0 ,
'naval_engineering' : 5,
'destroyer_practical' : 5,
'cruiser_practical' : 5,
'capitalship_practical' : 2.5,
'carrier_practical' : 0 ,
'submarine_engineering' : 10 ,
'submarine_practical' : 5,
'electornicegineering_theory' : 5 ,
'electornicegineering_practical' : 5,
'automotive_theory' : 10 ,
'armour_practical' : 5,
'aeronautic_engineering' : 10 ,
'single_engine_aircraft_practical' : 10 ,
'twin_engine_aircraft_practical' : 5,
'four_engine_aircraft_practical' : 2.5,
'spearhead_theory' : 10 ,
'superior_firepower_theory' : 0 ,
'grand_battleplan_theory' : 0 ,
'human_wave_theory' : 0 ,
'land_doctrine_practical': 1,
'naval_doctrine_practical' : 0 ,
'base_strike_doctrine' : 0,
'fleet_in_being_doctrine' : 0 ,
'air_doctrine_practical' : 0 ,
'fighter_focus' : 2.5,
'cas_focus' : 2.5 ,
'tac_focus' : 2.5,
'nav_focus' : 1,
'strategic_air_focus' : 0 ,
'sealane_interdiction_doctrine' : 5,
'mechanicalengineering_theory' : 15,
'chemical_engineering' : 10 ,
'jetengine_theory' : 0 ,
'jetengine_practical' : 0 ,
'nuclear_physics' : 1,
'nuclear_bomb' : 0 ,
'transport_practical' : 2.5,
'officers_ratio' : 1.5,
'construction_practical' : 5,
'combat_medicine' : 1,
'first_aid' : 1,
'agriculture' : 4,
'industral_production' : 4,
'industral_efficiency' : 4,
'oil_to_coal_conversion' : 2,
'supply_production' : 4,
'electronic_mechanical_egineering' : 1,
'radio_technology' : 1,
'radio_detection_equipment' : 1,
'radio' : 1,
'census_tabulation_machine' : 1,
'mechnical_computing_machine' : 1,
'encryption_machine' : 1,
'construction_engineering' : 1,
'advanced_construction_engineering' : 1,
'rocket_tests' : 1,
'atomic_research' : 1,
'oil_refinning' : 1,
'steel_production' : 2,
'raremetal_refinning_techniques' : 2,
'coal_processing_technologies' : 2,
'education' : 1,
'supply_transportation' : 1,
'supply_organisation' : 1,
'civil_defence' : 1,
'heavy_aa_guns' : 2,
'militia_smallarms' : 1,
'militia_support' : 1,
'militia_guns' : 1,
'militia_at' : 1,
'infantry_activation' : 1,
'smallarms_technology' : 1,
'infantry_support' : 1,
'infantry_guns' : 1,
'infantry_at' : 1,
'schwerpunkt' : 0,
'blitzkrieg' : 2,
'mobile_warfare' : 2,
'elastic_defence' : 2,
'operational_level_command_structure' : 1,
'tactical_command_structure' : 0,
'mechanized_offensive' : 2,
'delay_doctrine' : 0,
'integrated_support_doctrine' : 2,
'infantry_warfare' : 2,
'special_forces' : 1,
'assault_concentration' : 1,
'central_planning' : 0,
'mass_assault' : 0,
'peoples_army' : 2,
'large_front' : 0,
'guerilla_warfare' : 0,
'operational_level_organisation' : 1,
'cavalry_smallarms' : 3,
'cavalry_support' : 3,
'cavalry_guns' : 3,
'cavalry_at' : 3,
'mortorised_infantry' : 1,
'art_barrell_ammo' : 3,
'art_carriage_sights' : 3,
'lighttank_brigade' : 1,
'lighttank_armour' : 1,
'single_engine_aircraft_design' : 1,
'basic_aeroengine' : 1 ,
'basic_small_fueltank' : 1 ,
'basic_single_engine_airframe' : 1 ,
'basic_aircraft_machinegun' : 1,
'twin_engine_aircraft_design' : 1,
'aeroengine' : 1,
'basic_twin_engine_airframe' : 1,
'basic_four_engine_airframe' : 1,
'battlecruiser_technology' : 1,
'battlecruiser_antiaircraft' : 2,
'battlecruiser_engine' : 3,
'battlecruiser_armour' : 3,
'battleship_technology' : 1,
'capitalship_armament' : 3,
'battleship_antiaircraft' : 2,
'battleship_engine' : 2,
'battleship_armour' : 3,
'destroyer_technology' : 1,
'destroyer_armament' : 1,
'destroyer_engine' : 1,
'destroyer_armour' : 1,
'heavycruiser_technology' : 1,
'heavycruiser_armament' : 3,
'heavycruiser_antiaircraft' : 2,
'heavycruiser_engine' : 3,
'heavycruiser_armour' : 3,
'lightcruiser_technology' : 1,
'lightcruiser_armament' : 2,
'lightcruiser_antiaircraft' : 2,
'lightcruiser_engine' : 3,
'lightcruiser_armour' : 2,
'smallwarship_radar' : 1,
'submarine_technology' : 1,
'submarine_engine' : 1,
'submarine_sonar' : 1,
'submarine_hull' : 1,
'sea_lane_defence' : 1,
'fire_control_system_training' : 1,
'fleet_auxiliary_submarine_doctrine' : 1,
'trade_interdiction_submarine_doctrine' : 1,
'cruiser_warfare' : 1,
'submarine_crew_training' : 1,
'fighter_pilot_training' : 2,
'fighter_groundcrew_training' : 2,
'interception_tactics' : 2,
'fighter_ground_control' : 0,
'bomber_targerting_focus' : 2,
'fighter_targerting_focus' : 2,
'cas_pilot_training' : 2,
'cas_groundcrew_training' : 2,
'ground_attack_tactics' : 2,
'forward_air_control' : 2,
'battlefield_interdiction' : 2,
'tac_pilot_training' : 2,
'tac_groundcrew_training' : 2,
'interdiction_tactics' : 2,
'logistical_strike_tactics' : 1,
'installation_strike_tactics' : 1,
'airbase_strike_tactics' : 2,
'tactical_air_command' : 2,
'nav_pilot_training' : 1,
'nav_groundcrew_training' : 1,
'portstrike_tactics' : 0,
'navalstrike_tactics' : 0,
'naval_air_targeting' : 0,
'naval_tactics' : 0,
'heavy_bomber_pilot_training' : 1,
'heavy_bomber_groundcrew_training' : 1 ,
'strategic_bombardment_tactics' : 1,
'airborne_assault_tactics' : 0,
'strategic_air_command' : 0,
'cas_development' : 1,
'nav_development' : 1,
'basic_strategic_bomber' : 1,
'training_laws' : 'advanced_training',
'press_laws' : 'propaganda_press',
'industrial_policy_laws' : 'mixed_industry',
'education_investment_law' : 'medium_large_education_investment',
'economic_law' : 'basic_mobilisation',
'conscription_law' : 'volunteer_army',
'civil_law' : 'totalitarian_system'
}