DROP TABLE nfl_game_drives PURGE;
DROP TABLE nfl_game PURGE;
DROP TABLE nfl_game_details PURGE;
DROP TABLE nfl_game_player PURGE;
DROP TABLE nfl_game_teamstats PURGE;
DROP TABLE nfl_game_playbyplay PURGE;

CREATE TABLE nfl_game_drives
	(
	endTransition varchar2(26),
	endYardLine varchar2(9),
	endedWithScore varchar2(26),
	firstDowns number,
	gameClockEnd timestamp(2),
	gameClockStart timestamp(2),
	howEndedDescription varchar2(26),
	howStartedDescription varchar2(26),
	inside20 varchar2(6),
	orderSequence number,
	playCount number,
	playIdEnded number,
	playIdStarted number,
	playSeqEnded number,
	playSeqStarted number,
	quarterEnd number,
	quarterStart number,
	realStartTime varchar2(26),
	startTransition varchar2(26),
	startYardLine varchar2(26),
	timeOfPossession interval day(2) to second (2),
	yards number,
	yardsPenalized number,
	abbreviation varchar2(4),
	nickName varchar2(26),
	gameId varchar2(50)
	);

CREATE TABLE nfl_game
	(
	id VARCHAR2(50), 
	gameTime TIMESTAMP, 
	gsisId INTEGER CONSTRAINT nfl_game_pk PRIMARY KEY, 
	gameDetailId VARCHAR2(50), 
	awayabbreviation VARCHAR2(4),
	awayfullName VARCHAR2(26), 
	awayid VARCHAR2(50), 
	awaynickName VARCHAR2(26), 
	awaycityStateRegion VARCHAR2(26),
	homeabbreviation VARCHAR2(4), 
	homefullName VARCHAR2(26), 
	homeid VARCHAR2(50), 
	homenickName VARCHAR2(26),
	homecityStateRegion VARCHAR2(26), 
	seasonValue INTEGER, 
	weekId VARCHAR2(50), 
	seasonType VARCHAR2(10),
	weekValue INTEGER, 
	weekType VARCHAR2(10), 
	venuefullName VARCHAR2(50), 
	venuecity VARCHAR2(26), 
	venuestate VARCHAR2(4)
	);

CREATE TABLE nfl_game_details
	(
	id VARCHAR2(50),
	attendance INTEGER,
	homePointsOvertime VARCHAR2(26),
	homePointsTotal INTEGER,
	homePointsQ1 INTEGER,
	homePointsQ2 INTEGER,
	homePointsQ3 INTEGER,
	homePointsQ4 INTEGER,
	homeTimeoutsUsed INTEGER,
	homeTimeoutsRemaining INTEGER,
	stadium VARCHAR2(50),
	startTime TIMESTAMP,
	visitorPointsOvertime VARCHAR2(26),
	visitorPointsOvertimeTotal INTEGER,
	visitorPointsQ1 INTEGER,
	visitorPointsQ2 INTEGER,
	visitorPointsQ3 INTEGER,
	visitorPointsQ4 INTEGER,
	visitorPointsTotal INTEGER,
	visitorTimeoutsUsed INTEGER,
	visitorTimeoutsRemaining INTEGER,
	homePointsOvertimeTotal INTEGER,
	homeabbreviation VARCHAR2(4),
	homenickName VARCHAR2(26),
	visitorabbreviation VARCHAR2(4),
	visitornickName VARCHAR2(26)
	);

CREATE TABLE nfl_game_player
	(
	createdDate TIMESTAMP,
	id VARCHAR2(50),
	lastModifiedDate TIMESTAMP,
	gameid VARCHAR2(50),
	defensiveAssists NUMBER,
	defensiveInterceptions NUMBER,
	defensiveInterceptionsYards NUMBER,
	defensiveForcedFumble NUMBER,
	defensivePassesDefensed NUMBER,
	defensiveSacks NUMBER,
	defensiveSafeties NUMBER,
	defensiveSoloTackles NUMBER,
	defensiveTotalTackles NUMBER,
	defensiveTacklesForALoss NUMBER,
	touchdownsDefense NUMBER,
	fumblesLost NUMBER,
	fumblesTotal NUMBER,
	kickReturns NUMBER,
	kickReturnsLong NUMBER,
	kickReturnsTouchdowns NUMBER,
	kickReturnsYards NUMBER,
	kickingFgAtt NUMBER,
	kickingFgLong NUMBER,
	kickingFgMade NUMBER,
	kickingXkAtt NUMBER,
	kickingXkMade NUMBER,
	passingAttempts NUMBER,
	passingCompletions NUMBER,
	passingTouchdowns NUMBER,
	passingYards NUMBER,
	passingInterceptions NUMBER,
	puntReturns NUMBER,
	puntingAverageYards NUMBER,
	puntingLong NUMBER,
	puntingPunts NUMBER,
	puntingPuntsInside20 NUMBER,
	receivingReceptions NUMBER,
	receivingTarget NUMBER,
	receivingTouchdowns NUMBER,
	receivingYards NUMBER,
	rushingAttempts NUMBER,
	rushingAverageYards NUMBER,
	rushingTouchdowns NUMBER,
	rushingYards NUMBER,
	kickoffReturnsTouchdowns NUMBER,
	kickoffReturnsYards NUMBER,
	puntReturnsLong NUMBER,
	opponentFumbleRecovery NUMBER,
	totalPointsScored NUMBER,
	kickReturnsAverageYards NUMBER,
	puntReturnsAverageYards NUMBER,
	puntReturnsTouchdowns NUMBER,
	position VARCHAR2(10),
	jerseyNumber INTEGER,
	abbreviation VARCHAR2(4),
	nickName VARCHAR2(26),
	displayName VARCHAR2(128),
	firstName VARCHAR2(50),
	lastName VARCHAR2(50),
	seasonid VARCHAR2(50),
	weekid VARCHAR2(50)
	);

CREATE TABLE nfl_game_playbyplay
	(
	clockTime timestamp,
	down number,
	driveNetYards number,
	drivePlayCount number,
	driveSequenceNumber number,
	driveTimeOfPossession interval day(2) to second (2),
	endClockTime timestamp,
	endYardLine varchar2(10),
	firstDown varchar2(10),
	goalToGo varchar2(10),
	isBigPlay varchar2(10),
	latestPlay varchar2(10),
	nextPlayIsGoalToGo varchar2(10),
	nextPlayType varchar2(26),
	orderSequence number,
	penaltyOnPlay varchar2(10),
	playClock number,
	playDeleted varchar2(10),
	playDescription varchar2(256),
	playDescriptionWithJerseyNumbers varchar2(256),
	playId number,
	playReviewStatus varchar2(10),
	playType varchar2(26),
	prePlayByPlay varchar2(26),
	quarter number,
	scoringPlay varchar2(10),
	scoringPlayType varchar2(10),
	scoringTeam varchar2(50),
	shortDescription varchar2(128),
	specialTeamsPlay varchar2(10),
	stPlayType varchar2(26),
	timeOfDay timestamp,
	yardLine varchar2(10),
	yards number,
	yardsToGo number,
	abbreviation varchar2(4),
	nickName varchar2(26),
	gameId varchar2(50)
	);

CREATE TABLE nfl_game_teamstats
	(
	opponentpassingNetYards number, 
	opponentscrimmageYds number,
	opponentpassingAverageYards number,
	opponentrushingAverageYards number,
	opponenttotalPointsScored number,
	opponentfumblesLost number,
	opponentpassingInterceptions number,
	opponentpassingSacked number,
	opponentdown3rdAttempted number,
	opponentdown3rdFdMade number,
	opponentgamesPlayed number,
	opponentrushingYards number,
	abbreviation varchar2(4),
	passingNetYards number,
	scrimmageYds number,
	passingAverageYards number,
	rushingAverageYards number,
	scrimmagePlays number,
	totalPointsScored number,
	fumblesLost number,
	rushingYards number,
	passingInterceptions number,
	passingSacked number,
	down3rdAttempted number,
	down3rdFdMade number,
	timeOfPossSeconds number,
	penaltiesTotal number,
	gamesPlayed number,
	gameId varchar2(50)
	);

